name: load_data_to_firestore
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  dto:
    path: ../dto
  firedart: ^0.9.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
