import 'package:dto/transaction.dart';
import 'package:load_data_to_firestore/users.dart';

List<Transaction> transactions = [
  Transaction(
    title: "Salle Royale",
    description: "Location pour soirée grandiose",
    amount: 500.0,
    date: DateTime(2023, 8, 19),
    owner: users[0],
    concerns: [users[0], users[2], users[4]],
  ),
  Transaction(
    title: "Dîner Gourmand",
    description: "Traiteur de plaisirs culinaires",
    amount: 300.0,
    date: DateTime(2023, 8, 19),
    owner: users[1],
    concerns: [users[1], users[3], users[5]],
  ),
  Transaction(
    title: "Feux d'Artifice",
    description: "Étincelles dans la nuit",
    amount: 200.0,
    date: DateTime(2023, 8, 20),
    owner: users[2],
    concerns: [users[0], users[2], users[3]],
  ),
  Transaction(
    title: "Robe Étincelante",
    description: "Pour briller sous les projecteurs",
    amount: 150.0,
    date: DateTime(2023, 8, 20),
    owner: users[3],
    concerns: [users[1], users[3], users[5]],
  ),
  Transaction(
    title: "Cours de Danse",
    description: "Pour impressionner sur la piste",
    amount: 80.0,
    date: DateTime(2023, 8, 21),
    owner: users[4],
    concerns: [users[0], users[2], users[4]],
  ),
  Transaction(
    title: "Pansements Ampoules",
    description: "Achats préventifs pour la soirée",
    amount: 20.0,
    date: DateTime(2023, 8, 21),
    owner: users[5],
    concerns: [users[1], users[3], users[5]],
  ),
  Transaction(
    title: "Crampes de Danse",
    description: "Consultation d'urgence",
    amount: 50.0,
    date: DateTime(2023, 8, 21),
    owner: users[0],
    concerns: [users[0], users[2], users[4]],
  ),
  Transaction(
    title: "Talons Impressionnants",
    description: "Achats pour paraître plus grand(e)",
    amount: 75.0,
    date: DateTime(2023, 8, 21),
    owner: users[1],
    concerns: [users[1], users[3], users[5]],
  ),
  Transaction(
    title: "Tapis Rouge",
    description: "Pour entrées spectaculaires",
    amount: 30.0,
    date: DateTime(2023, 8, 21),
    owner: users[2],
    concerns: [users[0], users[2], users[3]],
  ),
  Transaction(
    title: "Piste de Danse VIP",
    description: "Réservation exclusive mondiale",
    amount: 1000.0,
    date: DateTime(2023, 8, 22),
    owner: users[3],
    concerns: [users[1], users[3], users[5]],
  ),
  Transaction(
    title: "Chapeaux Fous",
    description: "Pour suivre le thème de la soirée",
    amount: 45.0,
    date: DateTime(2023, 8, 22),
    owner: users[4],
    concerns: [users[0], users[2], users[4]],
  ),
  Transaction(
    title: "Discours Inspirants",
    description: "Cours intensif pour briller à la tribune",
    amount: 150.0,
    date: DateTime(2023, 8, 22),
    owner: users[5],
    concerns: [users[1], users[3], users[5]],
  ),
  Transaction(
    title: "Feu d'Artifice Précoce",
    description: "Oups, c'était une étincelle accidentelle",
    amount: 15.0,
    date: DateTime(2023, 8, 22),
    owner: users[0],
    concerns: [users[0], users[2], users[4]],
  ),
  Transaction(
    title: "Coach de Selfies",
    description: "Apprenez l'art de la pose parfaite",
    amount: 40.0,
    date: DateTime(2023, 8, 23),
    owner: users[1],
    concerns: [users[1], users[3], users[5]],
  ),
  Transaction(
    title: "Achats de Confettis",
    description: "Pour rendre chaque moment éclatant",
    amount: 10.0,
    date: DateTime(2023, 8, 23),
    owner: users[2],
    concerns: [users[0], users[2], users[3]],
  ),
  Transaction(
    title: "Chauffeur de Limo",
    description: "Arrivez en style... et en retard",
    amount: 200.0,
    date: DateTime(2023, 8, 24),
    owner: users[3],
    concerns: [users[1], users[3], users[5]],
  ),
  Transaction(
    title: "Élégance Extrême",
    description: "Achat de gants blancs assortis",
    amount: 25.0,
    date: DateTime(2023, 8, 24),
    owner: users[4],
    concerns: [users[0], users[2], users[4]],
  ),
  Transaction(
    title: "Cours de Rires Contagieux",
    description: "Fou rire garanti en une leçon",
    amount: 30.0,
    date: DateTime(2023, 8, 24),
    owner: users[5],
    concerns: [users[1], users[3], users[5]],
  ),
  Transaction(
    title: "Micro pour Discours Épiques",
    description: "Se sentir comme un leader inspirant",
    amount: 50.0,
    date: DateTime(2023, 8, 24),
    owner: users[0],
    concerns: [users[0], users[2], users[4]],
  ),
  Transaction(
    title: "Photobooth Fantastique",
    description: "Souvenirs photogéniques garantis",
    amount: 70.0,
    date: DateTime(2023, 8, 25),
    owner: users[1],
    concerns: [users[1], users[3], users[5]],
  ),
];
